# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: L2_L3_Network
# label used for menu selection
label: L2_L3 Network
description: "** LOAD BASELINE FIRST ** Hybrid L2/L3 Network Config"
# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:
# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - myCollection
# ---------------------------------------------------------------------
# end of preamble section
# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
 - name: INTF_UNTRUST
    description: internet Interface
    default: ethernet1/1
    type_hint: dropdown
    source: interface_names
  - name: INTF_TRUST_2
    description: internal Interface
    default: ethernet1/2
    type_hint: dropdown
    source: interface_names
  - name: INTF_TRUST_3
    description: internal Interface
    default: ethernet1/3
    type_hint: dropdown
    source: interface_names
  - name: L2_ZONE_TRUST
    description: internal zone name
    default: internal
    type_hint: text
  - name: L3_ZONE_UNTRUST
    description: internet zone name
    default: internet
    type_hint: text
  - name: L3_ZONE_TRUST
    description: internal untrust zone name
    default: internal
    type_hint: text
  - name: INTF_VLAN
    description: vlan interface
    default: vlan.1

  - name: DHCP_NETMASK
    description: dhcp pool netmask
    default: 255.255.255.0
    type_hint: ip_address
  - name: DHCP_GATEWAY
    description: dhcp pool default gateway ip address
    default: 192.168.74.1/24
    type_hint: ip_address
  - name: DHCP_POOL_RANGE
    description: dhcp pool ip address range
    default: 192.168.74.2-192.168.45.100
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section
# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order
# There is a variable called snippets that we can use to auto-generate this section for us
snippets:
  - name: interface_management_profile
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/profiles
    element: |-
        <interface-management-profile>
                    <entry name="internal">
                      <ping>yes</ping>
                    </entry>
                  </interface-management-profile>
  - name: ethernet 1/1
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
      <ethernet>
        <entry name="{{ INTF_UNTRUST }}">
                      <layer3>
                        <ndp-proxy>
                          <enabled>no</enabled>
                        </ndp-proxy>
                        <lldp>
                          <enable>no</enable>
                        </lldp>
                        <dhcp-client/>
                        <interface-management-profile>internal</interface-management-profile>
                      </layer3>
                    </entry>
      </ethernet>
  # To do: add in for loop for each interface 
  # L2 Interface variable will be type check box list 

  
  
  - name: ethernet 1/2
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
      <ethernet>
        <entry name={{ INTF_TRUST }}>
                      <layer2>
                        <lldp>
                          <enable>no</enable>
                        </lldp>
                      </layer2>
                    </entry>
      </ethernet>
  
    
  - name: vlan.1
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface
    element: |-
        <vlan>
                    <units>
                      <entry name="{{ INTF_VLAN }}">
                        <ipv6>
                          <neighbor-discovery>
                            <router-advertisement>
                              <enable>no</enable>
                            </router-advertisement>
                          </neighbor-discovery>
                        </ipv6>
                        <ndp-proxy>
                          <enabled>no</enabled>
                        </ndp-proxy>
                        <adjust-tcp-mss>
                          <enable>no</enable>
                        </adjust-tcp-mss>
                        <ip>
                          <entry name="{{ DHCP_GATEWAY }}"/>
                        </ip>
                        <interface-management-profile>internal</interface-management-profile>
                      </entry>
                    </units>
                  </vlan>
  - name: vlan-profile
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network
    element: |-
        <vlan>
                  <entry name="Vlan">
                    <interface>
                      <member>{{ INTF_TRUST_2 }}</member>
                      <member>{{ INTF_TRUST_3 }}</member>
                    </interface>
                    <virtual-interface>
                      <interface>{{ INTF_VLAN }}</interface>
                    </virtual-interface>
                  </entry>
                </vlan>
  - name: L3_Untrust
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/zone
    element: |-
        <entry name="{{ L3_ZONE_UNTRUST }}">
                      <network>
                        <layer3>
                          <member>{{ INTF_UNTRUST }}</member>
                        </layer3>
                        <log-setting>default</log-setting>
                      </network>
                    </entry>
  - name: L3_Trust
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/zone
    element: |-
        <entry name="{{ L3_ZONE_TRUST }}">
                      <network>
                        <layer3>
                          <member>{{ INTF_VLAN }}</member>
                        </layer3>
                        <log-setting>default</log-setting>
                      </network>
                    </entry>
  - name: L2-Trust
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/zone
    element: |-
        <entry name="{{ L2_ZONE_TRUST }}">
                      <network>
                        <layer2>
                          <member>{{ INT_TRUST_2 }}</member>
                          <member>{{ INT_TRUST_3 }}</member>
                        </layer2>
                        <log-setting>default</log-setting>
                      </network>
                    </entry>
  - name: routing_options
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]/protocol/bgp
    element: |-
        <routing-options>
                          <graceful-restart>
                            <enable>yes</enable>
                          </graceful-restart>
                        </routing-options>
  - name: rip
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]/protocol
    element: |-
        <rip>
                        <enable>no</enable>
                      </rip>
  - name: ospf
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]/protocol
    element: |-
        <ospf>
                        <enable>no</enable>
                      </ospf>
  - name: ospfv3
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]/protocol
    element: |-
        <ospfv3>
                        <enable>no</enable>
                      </ospfv3>
  - name: virtual_router_Interfaces
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]
    element: |-
        <interface>
                      <member>{{ INT_UNTRUST }}</member>
                      <member>{{ INTF_VLAN }}</member>
                    </interface>
  - name: ecmp
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]
    element: |-
        <ecmp>
                      <algorithm>
                        <ip-modulo/>
                      </algorithm>
                    </ecmp>
  - name: dhcp
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network
    element: |-
        <dhcp>
                  <interface>
                    <entry name="{{ INTF_VLAN }}">
                      <server>
                        <option>
                          <lease>
                            <unlimited/>
                          </lease>
                          <gateway>{{ DHCP_GATEWAY }}</gateway>
                          <subnet-mask>{{ DHCP_NETMASK }}</subnet-mask>
                          <dns>
                            <primary>inherited</primary>
                            <secondary>inherited</secondary>
                          </dns>
                          <inheritance>
                            <source>{{ INTF_UNTRUST }}</source>
                          </inheritance>
                        </option>
                        <ip-pool>
                          <member>{{ DHCP_POOL_RANGE }}</member>
                        </ip-pool>
                        <mode>auto</mode>
                      </server>
                    </entry>
                  </interface>
                </dhcp>
  - name: import
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]
    element: |-
        <import>
                    <network>
                      <interface>
                        <member>{{ INTF_UNTRUST }}</member>
                        <member>e{{ INTF_TRUST_2 }}</member>
                        <member>e{{ INTF_TRUST_3 }}</member>
                        <member>{{ INTF_VLAN }}</member>
                      </interface>
                    </network>
                  </import>
  - name: Security_Policies
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase/security/rules
    element: |-
        <entry name="open-internet" uuid="7c22c98e-b071-4b61-ba03-9b4b27a44733">
                          <to>
                            <member>{{ L3_ZONE_UNTRUST }}</member>
                          </to>
                          <from>
                            <member>{{ L3_ZONE_TRUST }}</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <source-user>
                            <member>any</member>
                          </source-user>
                          <category>
                            <member>any</member>
                          </category>
                          <application>
                            <member>any</member>
                          </application>
                          <service>
                            <member>application-default</member>
                          </service>
                          <source-hip>
                            <member>any</member>
                          </source-hip>
                          <destination-hip>
                            <member>any</member>
                          </destination-hip>
                          <action>allow</action>
                          <log-setting>default</log-setting>
                        </entry>
  - name: NAT_Policies
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/rulebase
    element: |-
        <nat>
                      <rules>
                        <entry name="internet" uuid="275ecfcb-752e-4bbc-81b0-00f67c08e8ac">
                          <source-translation>
                            <dynamic-ip-and-port>
                              <interface-address>
                                <interface>ethernet1/1</interface>
                              </interface-address>
                            </dynamic-ip-and-port>
                          </source-translation>
                          <to>
                            <member>{{ L3_ZONE_UNTRUST }}</member>
                          </to>
                          <from>
                            <member>{{ L3_ZONE_TRUST }}</member>
                          </from>
                          <source>
                            <member>any</member>
                          </source>
                          <destination>
                            <member>any</member>
                          </destination>
                          <service>any</service>
                        </entry>
                      </rules>
                    </nat>
# ---------------------------------------------------------------------
# end of snippets section