# workflow demo that cleans the config, does a content update, then configures a basic internet gateway

name: homeskillet_config_workflow_panos_v90
label: v9.0 Configuration Only workflow
description: |
  this workflow steps through the configuration stages without config reset or content updates

type: workflow

labels:
    collection:
      - Homeskillet
      - Configure

variables:
# in the future can let the user choose the network layer option as a workflow stage

snippets:
# workflow stages for config only
# day 1 baseline configuration
  - name: homeskillet_base_panos_v90
# network layer and zone configuration
  - name: homeskillet_L3network_panos_v90
# security policies
  - name: homeskillet_policies_panos_v90