name: vars_test_homeSkillet
label: see active vars
description: vars testing

type: template

extends:

labels:
  collection:
    - HomeSkillet

variables:
  - name: test_var_name
    description: test var name
    default: some var
    type_hint: text

snippets:
  - name: vars_output
    file: vars_output.txt