# workflow demo that cleans the config, does a content update, then configures a basic internet gateway

name: homeskillet_demo_workflow_panos_v90
label: v9.0 Full demo workflow
description: |
  this workflow steps through a rollback to starter config, content updates, and then load in
  the IronSkillet-like day 1, network and zones, then security policies

type: workflow

labels:
    collection:
      - Homeskillet
      - Configure

variables:
# in the future can let the user choose the network layer option as a workflow stage

snippets:
# workflow stages for full demo
# reset config to empty state
  - name: import_empty_config_HomeSkillet
# content updates to latest version
  - name: ngfw_content_update
# day 1 baseline configuration
  - name: homeskillet_base_panos_v90
# network layer and zone configuration
  - name: homeskillet_L3network_panos_v90
# security policies
  - name: homeskillet_policies_panos_v90