# gold security templates for top level security including threat, URL, or WF subscriptions
# includes an additional security rule for strict file blocking of unknown url category

name: homeskillet_policies_panos_v90
label: v9.0 Step 3 - HomeSkillet Security policy configuration
description: "** LOAD STEP 2 FIRST ** v9.0 Home Skillet Internet Gateway that loads after Step 2 network"
type: panos

labels:
    collection:
      - Homeskillet
      - Configure

variables:
  - name: ZONE_TRUST
    description: trust zone
    default: internal
    type_hint: text
  - name: ZONE_UNTRUST
    description: untrust zone name
    default: external
    type_hint: text

snippets:
  - name: profile_group_unknown_url
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group
    file: profile_group_unknown_url.xml
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: security_rules-security-rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
    file: security_rules.xml


