name: get_interface_lists_812E106E-EF84-48CC-A2CB-96F9D7DA7296

label: Output Value Capturing from a PAN-OS Device

description: |
  Get a set of lists to be used as dropdown menu options
type: rest

labels:
  collection:
    - lib

variables:
  - name: TARGET_IP
    description: Host
    default: 0.0.0.0
    type_hint: hidden
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: hidden

snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key

  - name: interfaces_list
    path: |
      https://{{ TARGET_IP }}/api/?type=config&action=set&action=complete&xpath=/config/devices/
      entry[@name='localhost.localdomain']/network/interface/ethernet&key={{ api_key }}
    output_type: xml
    outputs:
      - name: interface_names
        capture_pattern: ./completions/completion//@value
