# gold security templates for top level security including threat, URL, or WF subscriptions
# includes an additional security rule for strict file blocking of unknown url category

name: labinabox_v90
label: v9.0 Step 2 - Lab in a Box variant of HomeSkillet - IronBox
description: "** LOAD BASELINE FIRST ** v9.0 IronBox Lab in a Box that tastes like HomeSkillet"
type: panos
extends:

labels:
    collection:
      - IronBox
      - Configure

variables:
#untrust interface - dhcp or static
  - name: INTF_UNTRUST
    description: Untrust Interface
    default: ethernet1/1
    type_hint: text
  - name: UNTRUST_TYPE
    description: Untrust interface address type [dhcp or static]
    default: dhcp
    type_hint: dropdown
    dd_list:
      - key: dhcp
        value: dhcp
      - key: static
        value: static
  - name: IP_11
    description: Untrust interface ip address [if static untrust]
    default: 192.168.55.20/24
    type_hint: text
# virtual router dg for static route if not dhcp inherited
  - name: UNTRUST_DG
    description: Untrust routing default gateway [if static untrust]
    default: 192.168.55.2
    type_hint: text
# trust interface - static only
  - name: INTF_TRUST
    description: trust Interface
    default: ethernet1/2
    type_hint: text
  - name: IP_12
    description: Trust interface ip address
    default: 192.168.45.20/24
    type_hint: text
# server connected interface
  - name: INTF_SERVER
    description: server connected Interface
    default: ethernet1/3
    type_hint: text
  - name: IP_13
    description: Trust interface ip address
    default: 192.168.35.20/24
    type_hint: text
# untrust - trust - servers zones
  - name: ZONE_TRUST
    description: trust zone
    default: trust
    type_hint: text
  - name: ZONE_UNTRUST
    description: untrust zone name
    default: untrust
    type_hint: text
  - name: ZONE_SERVER
    description: server zone name
    default: server
    type_hint: text
# dhcp server configuration
  - name: DHCP_NETMASK
    description: dhcp pool netmask
    default: 255.255.255.0
    type_hint: ip_address
  - name: DHCP_GATEWAY
    description: dhcp pool default gateway ip address
    default: 192.168.45.20
    type_hint: ip_address
  - name: DHCP_POOL_RANGE
    description: dhcp pool ip address range
    default: 192.168.45.100-192.168.45.250
    type_hint: text
# static dns if not inherited as dhcp client
  - name: dhcp_DNS_1
    description: primary dns server [if static untrust]
    default: 192.168.55.2
    type_hint: ip_address
  - name: dhcp_DNS_2
    description: secondary dns server [if static untrust]
    default: 8.8.8.8
    type_hint: ip_address

snippets:
  - name: network_profiles-network-profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/profiles
    file: network_profiles.xml
  - name: interface
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/interface
    file: interface.xml
  - name: virtual_router
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/virtual-router
    file: virtual_router.xml
  - name: zone
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/zone
    file: zone.xml
  - name: nat-source-nat-to-untrust
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/nat
    file: source_nat_to_untrust.xml
  - name: profile_group_unknown_url
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profile-group
    file: profile_group_unknown_url.xml
  - name: tag
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
  - name: security_rules-security-rules-gold
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
    file: security_rules_gold.xml
  - name: dhcp_server
    xpath: /config/devices/entry[@name='localhost.localdomain']/network/dhcp
    file: dhcp_server.xml


